-- Table: public.product

-- DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date character varying(255) COLLATE pg_catalog."default",
    asin character varying(255) COLLATE pg_catalog."default",
    product_title character varying(300) COLLATE pg_catalog."default",
    revenue character varying(255) COLLATE pg_catalog."default",
    ordered_units character varying(255) COLLATE pg_catalog."default",
    glance_views character varying(255) COLLATE pg_catalog."default",
    conversion_rate character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT product_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product
    OWNER to postgres;


----------------------------------------------------------------------------------------------- 

--Table: public.advertising

-- DROP TABLE IF EXISTS public.advertising;

CREATE TABLE IF NOT EXISTS public.advertising
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date character varying(255) COLLATE pg_catalog."default",
    asin character varying(255) COLLATE pg_catalog."default",
    cost character varying(255) COLLATE pg_catalog."default",
    clicks character varying(255) COLLATE pg_catalog."default",
    impression character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT advertising_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.advertising
    OWNER to postgres;

----------------------------------------------------------------------------------------------- 

-- Table: public.result

-- DROP TABLE IF EXISTS public.result;

CREATE TABLE IF NOT EXISTS public.result
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_advertising integer,
    id_product integer,
    prediction_id character varying(255) COLLATE pg_catalog."default",
    start_date character varying(255) COLLATE pg_catalog."default",
    end_date character varying(255) COLLATE pg_catalog."default",
    prediction character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT result_pkey PRIMARY KEY (id),
    CONSTRAINT result_id_advertising_fkey FOREIGN KEY (id_advertising)
        REFERENCES public.advertising (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT result_id_product_fkey FOREIGN KEY (id_product)
        REFERENCES public.product (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.result
    OWNER to postgres;


-------------------------------------------------------------------------------------------
-- Table: public.customer

-- DROP TABLE IF EXISTS public.customer;

CREATE TABLE IF NOT EXISTS customer
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_result integer,
    customer character varying(255) COLLATE pg_catalog."default",
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (id),
    CONSTRAINT customer_id_result_fkey FOREIGN KEY (id_result)
        REFERENCES public.result (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer
    OWNER to postgres;

-----------------------------------------------------------------------------------------